export default {
  recipesCacheWarning: 'Using cached recipes, last updated:',
  recipesLoadError: 'Something went wrong while loading the recipes',
  recipesSearchPlaceholder: 'Search for recipes...',
  recipesSortByDate: 'Sort by date',
  recipesSortByRating: 'Sort by rating',
  meanRatingSupport: 'Cocktails',
  meanRatingValue: 'Avg Rating',
  brandsSearchPlaceholder: 'Search for brands...',
  spiritsSearchPlaceholder: 'Search for spirits...',
  bottlesSpiritSelectPlaceholder: 'Select spirit...',
  menuEntryRecipes: 'Recipes',
  menuEntrySpirits: 'Top Spirits',
  menuEntryBrands: 'Top brands',
  menuEntryBottles: 'Top bottles',
};
